### ISSUE TITLE
ISO format too precise?

### ISSUE THREAD

**Issue by LarsEckart** [c-guntur/javasig-datetime-solutions#1]
Hello,

I finally get to try out your datetime kata, and it's going well so far, but instant's toString() conversion seems to be too precise.

https://github.com/LarsEckart/java_playground/runs/1848185503?check_suite_focus=true#step:5:69

Any thoughts about this? Like in your solutions, all I do is call java8Instant.toString()
Only other difference is that i updated the code to use junit5 instead.

**Comment by LarsEckart** [comment]
resolved via twitter DM

**Comment by c-guntur** [comment]
Thanks Lars!
